"""migrations

Revision ID: b4ce04edfdad
Revises: 
Create Date: 2026-04-04 11:45:38.108722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4ce04edfdad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_type', sa.String(length=40), nullable=True),
    sa.Column('zones', sa.String(length=40), nullable=True),
    sa.Column('area', sa.Integer(), nullable=True),
    sa.Column('style', sa.String(length=40), nullable=True),
    sa.Column('budget', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('phone', sa.String(length=12), nullable=True),
    sa.Column('email', sa.String(length=40), nullable=True),
    sa.Column('comment', sa.String(length=250), nullable=True),
    sa.Column('dispatch_date', sa.DateTime(), nullable=True),
    sa.Column('page_url', sa.String(length=80), nullable=True),
    sa.Column('utm_source', sa.String(length=80), nullable=True),
    sa.Column('referral_link', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('form')
    # ### end Alembic commands ###
