"""More chars in columns

Revision ID: b670c1ed12be
Revises: 36cec4e258dc
Create Date: 2026-04-04 18:50:39.244008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b670c1ed12be'
down_revision: Union[str, Sequence[str], None] = '36cec4e258dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('form', 'zones',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=250),
               existing_nullable=True)
    op.alter_column('form', 'comment',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=450),
               existing_nullable=True)
    op.drop_constraint(op.f('form_email_key'), 'form', type_='unique')
    op.drop_constraint(op.f('form_phone_key'), 'form', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('form_phone_key'), 'form', ['phone'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('form_email_key'), 'form', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('form', 'comment',
               existing_type=sa.String(length=450),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)
    op.alter_column('form', 'zones',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)
    # ### end Alembic commands ###
