"""Delete dublicate columns

Revision ID: d880357915d2
Revises: b670c1ed12be
Create Date: 2026-04-04 20:25:27.327326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd880357915d2'
down_revision: Union[str, Sequence[str], None] = 'b670c1ed12be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form', 'referral_link')
    op.drop_column('form', 'page_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form', sa.Column('page_url', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('form', sa.Column('referral_link', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
